### ISSUE TITLE
Errors when running generate

### ISSUE THREAD

**Issue by thejones** [feathersjs/feathers-cli#2]
TLDR - Changing `env.lookup()` to `env.register(require.resolve('generator-feathers'))` in generate.js seemed to fix this for me. I do not know enough about yeoman to know if this is machine specific or not. Hopefully this helps. 

When running any command (generate shown below) I receive the following: 
```
514 ajones:sandbox$feathers generate
feathers$

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: You don't seem to have a generator with the name feathers:app installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 0 registered generators run yo with the `--help` option.
    at Environment.create (/Users/ajones/git/forks/feathers-cli/node_modules/yeoman-environment/lib/environment.js:296:7)
    at Environment.run (/Users/ajones/git/forks/feathers-cli/node_modules/yeoman-environment/lib/environment.js:364:24)
    at CommandInstance.<anonymous> (/Users/ajones/git/forks/feathers-cli/lib/commands/generate.js:10:9)
    at EventEmitter.session.execCommandSet (/Users/ajones/git/forks/feathers-cli/node_modules/vorpal/dist/session.js:470:20)
    at EventEmitter.vorpal._exec (/Users/ajones/git/forks/feathers-cli/node_modules/vorpal/dist/vorpal.js:956:18)
    at EventEmitter.vorpal._execQueueItem (/Users/ajones/git/forks/feathers-cli/node_modules/vorpal/dist/vorpal.js:747:17)
    at EventEmitter.vorpal._queueHandler (/Users/ajones/git/forks/feathers-cli/node_modules/vorpal/dist/vorpal.js:731:10)
    at EventEmitter.vorpal.exec (/Users/ajones/git/forks/feathers-cli/node_modules/vorpal/dist/vorpal.js:678:10)
    at EventEmitter.Vorpal.parse (/Users/ajones/git/forks/feathers-cli/node_modules/vorpal/dist/vorpal.js:163:12)
    at exports.default (/Users/ajones/git/forks/feathers-cli/lib/index.js:14:40)
``` 

running `yo --help` shows that I do have them.
```
Available Generators:

  feathers
    hook
    middleware
    model
    service
```

**Comment by derek-watson** [comment]
@thejones it's weird, I found the opposite on my machine. When I use `env.register` on its own, I only get the `feathers:app` yeoman generator namespace, so I've left the call to `env.lookup()` in there after it in the PR above. 

Would you mind pulling the fix/2 branch and running `npm test`?

Thanks
