### ISSUE TITLE
feathers generate hook fails when some hooks are commented out

### ISSUE THREAD

**Issue by quentin-sommer** [feathersjs/feathers-cli#25]
## How to reproduce

Let it be a service with these hooks

```javascript
exports.before = {
  all: [computeAverage()],
  find: [],
  get: [],
  create: [],
  update: [
    /*auth.verifyToken(),
    auth.populateUser(),
    auth.restrictToAuthenticated()
    */
  ],
  patch: [],
  remove: []
};

exports.after = {
  all: [],
  find: [],
  get: [],
  create: [],
  update: [],
  patch: [],
  remove: []
};
```

when using `feathers generate hook` for this service and choosing **before hook** for the **update method**, the genrator will throw the following error

```TypeError: Cannot read property 'loc' of null
    at print (generator-feathers/node_modules/recast/lib/printer.js:72:37)
    at exports.printComments (generator-feathers/node_modules/recast/lib/comments.js:324:22)
    at printWithComments (generator-feathers/node_modules/recast/lib/printer.js:61:16)
    at print (generator-feathers/node_modules/recast/lib/printer.js:66:20)
    at Printer.print (generator-feathers/node_modules/recast/lib/printer.js:118:21)
    at Object.print (generator-feathers/node_modules/recast/main.js:6:33)
    at traverse.pre (generator-feathers/lib/transform.js:33:49)
    at visit (generator-feathers/node_modules/ast-traverse/ast-traverse.js:16:19)
    at visit (generator-feathers/node_modules/ast-traverse/ast-traverse.js:29:25)
    at visit (generator-feathers/node_modules/ast-traverse/ast-traverse.js:32:21)```

**Comment by daffl** [comment]
This might be related to https://github.com/feathersjs/generator-feathers/pull/111. Looks like that still didn't fix every case.
