### ISSUE TITLE
toLowerCase error

### ISSUE THREAD

**Issue by ElegantSudo** [feathersjs/feathers-cli#32]
```
local@MBP~$ generate service

? What do you want to call your service? 
? What type of service do you need? database
? For which database? NeDB
? Does your service require users to be authenticated? No
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.module.exports.string.downcase (/usr/local/lib/node_modules/feathers-cli/node_modules/i/lib/util.js:126:21)
    at Object.inflect.camelize (/usr/local/lib/node_modules/feathers-cli/node_modules/i/lib/methods.js:46:24)
    at Object.exports.addImport (/usr/local/lib/node_modules/feathers-cli/node_modules/generator-feathers/lib/transform.js:92:21)
    at importService (/usr/local/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/service/index.js:14:15)
    at module.exports.generators.Base.extend.writing (/usr/local/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/service/index.js:171:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/feathers-cli/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/feathers-cli/node_modules/run-async/index.js:26:25
    at new Promise (/usr/local/lib/node_modules/feathers-cli/node_modules/core-js/modules/es6.promise.js:191:7)
    at /usr/local/lib/node_modules/feathers-cli/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/feathers-cli/node_modules/yeoman-generator/lib/base.js:432:9
```

**Comment by daffl** [comment]
In `What do you want to call your service?` you have to give the service a name. It looks like you just skipped it.
