### ISSUE TITLE
Error when generating new service

### ISSUE THREAD

**Issue by firrae** [feathersjs/feathers-cli#47]
### Steps to reproduce
To reproduce for me, all I have to do is run `feathers generate service` at the top level folder of my application and then give it a name, select generic, and say yes or no to if it needs auth.

### Expected behavior
I expect to produce a baseline service file and the associated baseline test.

### Actual behavior
I'm using the latest version of the cli but when I try to generate a new service I get the error as follows:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: No function expression found after module.exports
    at Object.exports.addLastInFunction (C:\Users\Steven.Lambe\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\generator-feathers\lib\transform.js:81:11)
    at importService (C:\Users\Steven.Lambe\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\generator-feathers\generators\service\index.js:16:15)
    at module.exports.generators.Base.extend.writing (C:\Users\Steven.Lambe\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\generator-feathers\generators\service\index.js:171:5)
    at Object.<anonymous> (C:\Users\Steven.Lambe\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\yeoman-generator\lib\base.js:439:23)
    at C:\Users\Steven.Lambe\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\run-async\index.js:26:25
    at new Promise (C:\Users\Steven.Lambe\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\core-js\modules\es6.promise.js:191:7)
    at C:\Users\Steven.Lambe\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\run-async\index.js:25:19
    at C:\Users\Steven.Lambe\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\yeoman-generator\lib\base.js:440:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
feathers-cli 1.2.7

**NodeJS version**:
4.6.0

**Operating System**:
Windows 10 Pro

**Module Loader**:
Node

**Comment by daffl** [comment]
Did you change any of the code the generator normally modifies? `services/index.js` should look similar to https://github.com/feathersjs/feathers-chat/blob/master/src/services/index.js

**Comment by firrae** [comment]
Hm, I did, ok. I thought it would just build a skeleton service but I didn't think it would add it to the services index.
