### ISSUE TITLE
Error on Node version 7.1.0

### ISSUE THREAD

**Issue by shahabio** [feathersjs/feathers-cli#48]
CLI wont work anymore due to updating node to version 7.1.0

- machine: Windows 10
- node: 7.1.0 x64

```
C:\feathers-chat>feathers generate middleware
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at Console.log (console.js:43:16)
    at UI.prompt (C:\Users\Shahab\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\vorpal\dist\ui.js:233:17)
    at Vorpal.vorpal._prompt (C:\Users\Shahab\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\vorpal\dist\vorpal.js:612:15)
    at UI.attach (C:\Users\Shahab\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\vorpal\dist\ui.js:400:19)
```

**Comment by colbin8r** [comment]
+1, had the same problem. Downgraded to Node v6.9.1 and it worked like a charm (with Feathers 1.2.7) on Windows 10.

**Comment by beeplin** [comment]
+1, exactly the same. node 7.1.0, feathers-clie 1.2.7, windows 10

**Comment by ForsakenHarmony** [comment]
seems to work for me (windows 10 x64, node 7.2.1)

maybe try updating node?

**Comment by beeplin** [comment]
@ForsakenHarmony yes I just tested on node 7.2.1 and it's OK.

**Comment by marshallswain** [comment]
@shahabio It looks like the solution is to update to Node `7.2.1`.  Please reopen this issue if you find that there's still a problem.  

Thanks for reporting, @beeplin and @ForsakenHarmony.
