### ISSUE TITLE
Cannot create 'user' service

### ISSUE THREAD

**Issue by thosakwe** [feathersjs/feathers-cli#56]
### Steps to reproduce

I created a new application with the CLI, and didn't enable any authentication options, because I did not need any of the ones which were present, so no user service was generated.

Eventually, though, I needed one, so I ran `feathers generate service` and provided `user` as the name.

### Expected behavior
A MongoDB `user` service should be generated

### Actual behavior
Seems like the template expects you to be running `generate app` if the service name is `user`, because in this case, `providers` was undefined.

```
? What do you want to call your service? user
? What type of service do you need? database
? For which database? MongoDB
? Does your service require users to be authenticated? Yes
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: /usr/local/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/model/templates/mongoose.js:11
    9| const Schema = mongoose.Schema;
    10| 
 >> 11| const <%= name %>Schema = new Schema({<% if(name === 'user') { %><% for (var i = 0; i < providers.length; i++) { %>
    12|   <% if (providers[i] === 'local') { %>email: {type: String, required: true, unique: true},
    13|   password: { type: String, required: true },
    14|   <% } else { %><%= providers[i].name %>Id: { type: String },

Cannot read property 'length' of undefined
    at eval (eval at compile (/usr/local/lib/node_modules/feathers-cli/node_modules/ejs/lib/ejs.js:481:12), <anonymous>:17:37)
    at returnedFn (/usr/local/lib/node_modules/feathers-cli/node_modules/ejs/lib/ejs.js:512:17)
    at Object.exports.render (/usr/local/lib/node_modules/feathers-cli/node_modules/ejs/lib/ejs.js:316:37)
    at process (/usr/local/lib/node_modules/feathers-cli/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:18)
    at applyProcessingFunc (/usr/local/lib/node_modules/feathers-cli/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/feathers-cli/node_modules/mem-fs-editor/lib/actions/copy.js:51:16)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/feathers-cli/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/feathers-cli/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at constructor.writing (/usr/local/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/model/index.js:81:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/feathers-cli/node_modules/yeoman-generator/lib/base.js:439:23)
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
`feathers-cli` 1.2.7

**NodeJS version**:
7.3.0

**Operating System**:
macOS Sierra

**Browser Version**:
Irrelevant

**React Native Version**:
N/A

**Module Loader**:
`npm`

**Comment by marshallswain** [comment]
@thosakwe can you check if this is also an issue with a newly-generated app with no changes?  I'm wondering if this is a problem that's occurring because the AST transformations are breaking after manual changes to the code.

**Comment by daffl** [comment]
Unfortunately that version of the generator does not allow creating a user service after the fact because there is a bunch of conditionals based on the service name. You will probably have to set it up manually by generating a new app and copy the user service related things over.
